### ISSUE TITLE
Compile for PostgreSQL 12 Beta2 on Mac OS X

### ISSUE THREAD

**Issue by JamesInform** [plv8/plv8js#348]
Hi

I am trying to compile for PostgreSQL 12 Beta 2 on Mac OS X without success. Wether Tag 2.3.11 nor the master works.

I have done:
`make PG_CONFIG=path/to/my/pg_config`

Is this a known issue? Has anybody succeeded in compiling on Mac OS X?

Btw. I am using Mojave.

James

**Comment by JerrySievert** [comment]
you're ahead of me, I can get pg12 beta 2 to compile on macOS, but it won't install:

```
/usr/bin/install -c -m 644 utils/fmgrprotos.h '/tmp/pg12/include/postgresql/server/utils'
cp ./*.h '/tmp/pg12/include/postgresql/server'/
cp: ./dynloader.h: No such file or directory
make[2]: *** [install] Error 1
make[1]: *** [install-include-recurse] Error 2
make: *** [install-src-recurse] Error 2
```

I'll try to work through this so I can look at the plv8 build, but in the meantime, can you post your build error?

**Comment by JamesInform** [comment]
There seems to have been changes to the structure of the repository.

I ran into the same issue. Doing the following on my PostgreSQL GIT, I was able to build for Mac OS X without a problem:

1. make distclean
2. git pull
3. git checkout REL_12_BETA2
4. git clean -d -x -f
5. Then your configure ... make ... make install

I have found this solution in the following thread:

https://www.postgresql.org/message-id/CADOZ7s7OjESNCZ3%2BHqf%2BBPnq4ca54%2By9fAWdPpO-e49idOhcAg%40mail.gmail.com

**Comment by JerrySievert** [comment]
yeah, I found the same thread, ended up having to delete dynloader.h manually, even after the cleanup.

I'll take a look at some `#if` statements in the next day or so.

**Comment by JamesInform** [comment]
On PLV8 master, I get the following error:

`g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -stdlib=libc++ -std=c++11 -I. -I./ -I/Users/me/pg12b2/include/postgresql/server -I/Users/me/pg12b2/include/postgresql/internal -I/opt/local/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2  -fPIC -c -o plv8.o plv8.cc
In file included from plv8.cc:8:
./plv8.h:12:10: fatal error: 'v8.h' file not found
#include <v8.h>
         ^~~~~~
1 error generated.
make: *** [plv8.o] Error 1`

On v2.3.11, I get:

`/Users/me/pg12b2/include/postgresql/server/port/atomics/arch-x86.h:143:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17
      [-Wdeprecated-register]
        register char _res = 1;
        ^~~~~~~~~
plv8.cc:597:46: error: no member named 'argnull' in 'FunctionCallInfoBaseData'
                        args[i] = ToValue(fcinfo->arg[i], fcinfo->argnull[i], &argtypes[i]);
                                                          ~~~~~~  ^
plv8.cc:597:30: error: no member named 'arg' in 'FunctionCallInfoBaseData'; did you mean 'args'?
                        args[i] = ToValue(fcinfo->arg[i], fcinfo->argnull[i], &argtypes[i]);
                                                  ^~~
                                                  args
/Users/me/pg12b2/include/postgresql/server/fmgr.h:95:16: note: 'args' declared here
        NullableDatum args[FLEXIBLE_ARRAY_MEMBER];
                      ^
plv8.cc:694:45: error: no member named 'argnull' in 'FunctionCallInfoBaseData'
                args[i] = ToValue(fcinfo->arg[i], fcinfo->argnull[i], &argtypes[i]);
                                                  ~~~~~~  ^
plv8.cc:694:29: error: no member named 'arg' in 'FunctionCallInfoBaseData'; did you mean 'args'?
                args[i] = ToValue(fcinfo->arg[i], fcinfo->argnull[i], &argtypes[i]);
                                          ^~~
                                          args
/Users/me/pg12b2/include/postgresql/server/fmgr.h:95:16: note: 'args' declared here
        NullableDatum args[FLEXIBLE_ARRAY_MEMBER];
                      ^
plv8.cc:1387:21: error: use of undeclared identifier 'HeapTupleGetOid'
                        Oid langtupoid = HeapTupleGetOid(tuple);
                                         ^
plv8.cc:1514:4: error: unknown type name 'FunctionCallInfoData'
                        FunctionCallInfoData fake_fcinfo;
                        ^
2 warnings and 6 errors generated.
make: *** [plv8.o] Error 1`

**Comment by JerrySievert** [comment]
thanks. I'm about 20% through a port to pg12 on 3.0alpha, but I'm trying to do it during rest breaks (I'm unpacking from a move) - when that's complete, I'll work on a backport to 2.3, but I likely won't port it any further back.

**Comment by JamesInform** [comment]
Thanks for your effort. 
I hope the move went smoothly.

**Comment by JerrySievert** [comment]
I have a branch at https://github.com/JerrySievert/plv8 - r3.0alpha that it is compiling and working for me on macOS.

give that a try - I have a little more cleanup I want to do before opening up a PR and merging, and have not backported to 2.3 yet (this is the 3.0 alpha branch with a much newer v8, bigint support, and some other under the hood improvements)

**Comment by JamesInform** [comment]
Tried, doing this

`make PG_CONFIG=/Users/me/pg12b2/bin/pg_config`

I get that

`[707/707] LINK ./d8
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "3.0alpha"/' plv8_config.h.in > plv8_config.h
g++ -Wall -std=c++11 -fno-rtti -O2  -DJSONB_DIRECT_CONVERSION -Ibuild/v8/include -Ibuild/v8 -stdlib=libc++ -std=c++11 -I. -I./ -I/Users/me/pg12b2/include/postgresql/server -I/Users/me/pg12b2/include/postgresql/internal -I/opt/local/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2  -fPIC -c -o plv8.o plv8.cc
In file included from plv8.cc:26:
In file included from /Users/me/pg12b2/include/postgresql/server/commands/trigger.h:17:
In file included from /Users/me/pg12b2/include/postgresql/server/nodes/execnodes.h:26:
In file included from /Users/me/pg12b2/include/postgresql/server/utils/sharedtuplestore.h:18:
In file included from /Users/me/pg12b2/include/postgresql/server/storage/sharedfileset.h:20:
In file included from /Users/me/pg12b2/include/postgresql/server/storage/spin.h:54:
/Users/me/pg12b2/include/postgresql/server/storage/s_lock.h:226:2: warning: 'register' storage class specifier is
      deprecated and incompatible with C++17 [-Wdeprecated-register]
        register slock_t _res = 1;
        ^~~~~~~~~
In file included from plv8.cc:26:
In file included from /Users/me/pg12b2/include/postgresql/server/commands/trigger.h:17:
In file included from /Users/me/pg12b2/include/postgresql/server/nodes/execnodes.h:31:
In file included from /Users/me/pg12b2/include/postgresql/server/nodes/tidbitmap.h:26:
In file included from /Users/me/pg12b2/include/postgresql/server/utils/dsa.h:17:
In file included from /Users/me/pg12b2/include/postgresql/server/port/atomics.h:70:
/Users/me/pg12b2/include/postgresql/server/port/atomics/arch-x86.h:143:2: warning: 'register' storage class specifier
      is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register char _res = 1;
        ^~~~~~~~~
plv8.cc:650:46: error: no member named 'argnull' in 'FunctionCallInfoBaseData'
                        args[i] = ToValue(fcinfo->arg[i], fcinfo->argnull[i], &argtypes[i]);
                                                          ~~~~~~  ^
plv8.cc:650:30: error: no member named 'arg' in 'FunctionCallInfoBaseData'; did you mean 'args'?
                        args[i] = ToValue(fcinfo->arg[i], fcinfo->argnull[i], &argtypes[i]);
                                                  ^~~
                                                  args
/Users/me/pg12b2/include/postgresql/server/fmgr.h:95:16: note: 'args' declared here
        NullableDatum args[FLEXIBLE_ARRAY_MEMBER];
                      ^
plv8.cc:747:45: error: no member named 'argnull' in 'FunctionCallInfoBaseData'
                args[i] = ToValue(fcinfo->arg[i], fcinfo->argnull[i], &argtypes[i]);
                                                  ~~~~~~  ^
plv8.cc:747:29: error: no member named 'arg' in 'FunctionCallInfoBaseData'; did you mean 'args'?
                args[i] = ToValue(fcinfo->arg[i], fcinfo->argnull[i], &argtypes[i]);
                                          ^~~
                                          args
/Users/me/pg12b2/include/postgresql/server/fmgr.h:95:16: note: 'args' declared here
        NullableDatum args[FLEXIBLE_ARRAY_MEMBER];
                      ^
plv8.cc:1451:21: error: use of undeclared identifier 'HeapTupleGetOid'
                        Oid langtupoid = HeapTupleGetOid(tuple);
                                         ^
plv8.cc:1579:4: error: unknown type name 'FunctionCallInfoData'
                        FunctionCallInfoData fake_fcinfo;
                        ^
2 warnings and 6 errors generated.`

**Comment by JerrySievert** [comment]
just to make sure, you did:

```
$ git clone https://github.com/JerrySievert/plv8.git
$ cd plv8
$ git checkout r3.0alpha
```

**Comment by JerrySievert** [comment]
fyi, I've backported the changes to 2.3 and have released 2.3.12 which works under pg12.
