### ISSUE TITLE
Compilation errors with MSVC compiler

### ISSUE THREAD

**Issue by luber** [plv8/plv8js#461]
Looks like there are lines in code that are not compatible with the MSVC compiler:
![image](https://user-images.githubusercontent.com/3791692/136588496-4047b5a8-9eea-4a50-b2bb-e6b3ca9686e7.png)

Can someone help to fix this?

**Comment by JerrySievert** [comment]
which version of msvc is it using under the hood?

**Comment by luber** [comment]
@JerrySievert 
![image](https://user-images.githubusercontent.com/3791692/136604276-a94c18ac-8a7f-48da-9529-212649e51348.png)

**Comment by Suronixttv** [comment]
I have the same problem is there any known fix ?

**Comment by JerrySievert** [comment]
I've been actively working on 3.1, which should fix this, but do not have a release date yet.

in the mean time, you can use the 3.0alpha branch

**Comment by Suronixttv** [comment]
Okay thank you for the quick response. 

I tried building v3.0.0alpha and got the same error first. Then i found the commit where plv8_info() was added and pulled the last commit before the function was added. Sadly now v8 wont build anymore on version 7.0.302.
I couldn't seem to find a fix the last few days, seems like I have to wait untill the release.

For anyone with this Probleme last commit bevor plv8_info was added is in 3.0alpha
commit: 4c7cbe83f092f1a577c082dea4840cb4680e138c
